autoparts/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from autoparts import settings
from shop.views import MainView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', MainView.as_view(), name='main'),
    url(r'^price/', include('shop.urls')),
    url(r'^contact/', include('contact.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url

from shop.views import FullCatalogView, CatalogPartsView, CatalogOilsView, CatalogFiltersView, get_part_info, get_oil_info, get_search_result, \
    get_filter_info

urlpatterns = [
    url(r'^$', FullCatalogView.as_view(), name='catalog'),
    url(r'^parts/$', CatalogPartsView.as_view(), name='catalog_parts'),
    url(r'^oils/$', CatalogOilsView.as_view(), name='catalog_oils'),
    url(r'^filters/$', CatalogFiltersView.as_view(), name='catalog_filters'),
    url(r'^getpartinfo/', get_part_info, name='get_part_info'),
    url(r'^getoilinfo/', get_oil_info, name='get_oil_info'),
    url(r'^getfilterinfo/', get_filter_info, name='get_filter_info'),
    url(r'^search/', get_search_result, name='search'),
]

shop/models.py
from django.db import models
from shop.choices import *


class Parts(models.Model):
    name = models.CharField(max_length=200, verbose_name='Наименование')
    cat_num = models.CharField(max_length=200, verbose_name='Каталожный номер')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    applicability = models.CharField(max_length=300, blank=True, verbose_name='Применяемость')
    original_cat_num = models.CharField(max_length=200, blank=True, verbose_name='Оригинальный номер', default='')
    brand = models.CharField(max_length=100, blank=True, verbose_name='Бренд', default='')
    amount = models.IntegerField(blank=True, default='1', verbose_name='В наличии')

    class Meta:
        verbose_name = "Запчасть"
        verbose_name_plural = 'Запчасти'


class Oils(models.Model):
    name = models.CharField(max_length=200, verbose_name='Наименование')
    cat_num = models.CharField(max_length=200, verbose_name='Каталожный номер')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    brand = models.CharField(max_length=100, blank=True, verbose_name='Бренд', default='')
    amount = models.IntegerField(blank=True, default='1', verbose_name='В наличии')
    viscosity = models.CharField(max_length=10, choices=OIL_VISCOSITY_CHOICES, verbose_name='Вязкость')
    oil_type = models.CharField(max_length=20, choices=OIL_TYPE_CHOICES, verbose_name='Тип масла')
    size = models.IntegerField(default=1, verbose_name='Объем')

    class Meta:
        verbose_name = "Масло"
        verbose_name_plural = 'Масла'


class Filters(models.Model):
    name = models.CharField(max_length=200, verbose_name='Наименование')
    cat_num = models.CharField(max_length=200, verbose_name='Каталожный номер')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    brand = models.CharField(max_length=100, blank=True, verbose_name='Бренд', default='')
    size = models.CharField(max_length=200, blank=True, verbose_name='Размеры')
    amount = models.IntegerField(blank=True, default='1', verbose_name='В наличии')
    applicability = models.CharField(max_length=300, blank=True, verbose_name='Применяемость')

    class Meta:
        verbose_name = "Фильтр"
        verbose_name_plural = 'Фильтра'


class ImagesParts(models.Model):
    part = models.ForeignKey(Parts)
    image_url = models.URLField(max_length=500, verbose_name='URL изображения')


class ImagesOils(models.Model):
    oil = models.ForeignKey(Oils)
    image_url = models.URLField(max_length=500, verbose_name='URL изображения')


class ImagesFilters(models.Model):
    oil = models.ForeignKey(Filters)
    image_url = models.URLField(max_length=500, verbose_name='URL изображения')


class Task(models.Model):
    user = models.CharField(max_length=200)
    vin = models.CharField(max_length=100)
    text = models.CharField(max_length=2000)
    pub_date = models.DateTimeField(auto_now_add=True)
    mail = models.CharField(max_length=100)
    resolved = models.NullBooleanField(verbose_name='Решено', default=None)

    class Meta:
        verbose_name = "Заявка"
        verbose_name_plural = 'Заявки'


class Client(models.Model):
    name = models.CharField(max_length=200, verbose_name='Имя')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    car_info = models.CharField(max_length=500, blank=True, verbose_name='Данные об а/м')
    buyed_part = models.CharField(max_length=500, blank=True, verbose_name='Купленные з/ч')
    comment = models.CharField(max_length=1000, blank=True, verbose_name='Комментарий')

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = 'Клиенты'


class VinNum(models.Model):
    client = models.ForeignKey(Client)
    vin_num = models.CharField(max_length=18, verbose_name='Вин номер')

shop/views.py
# coding: utf-8
from django.db.models import Q
from django.http import HttpResponseServerError, HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.views.generic import ListView, FormView

from contact.forms import ContactForm
from contact.models import Contact
from shop.models import Parts, Oils, Filters
from slider.models import Slider


class MainView(FormView):
    model = Contact
    form_class = ContactForm
    context_object_name = 'user_list'
    template_name = 'main.html'
    success_url = '#'

    def get_context_data(self, **kwargs):
        context = super(MainView, self).get_context_data(**kwargs)
        context['contacts'] = Contact.objects.all()
        context['slider'] = Slider.objects.all()
        return context


class BaseCatalogView(FormView):
    form_class = ContactForm
    success_url = '#'
    template_name = 'shop.html'

    def get_context_data(self, **kwargs):
        context = super(BaseCatalogView, self).get_context_data(**kwargs)
        context['slider'] = Slider.objects.all()
        context['contacts'] = Contact.objects.all()
        return context


class FullCatalogView(BaseCatalogView):
    model = Parts
    context_object_name = 'parts_list'

    def get_context_data(self, **kwargs):
        context = super(FullCatalogView, self).get_context_data(**kwargs)
        context['parts_list'] = Parts.objects.all()
        context['oils_list'] = Oils.objects.all()
        context['filters_list'] = Filters.objects.all()
        return context


class CatalogPartsView(BaseCatalogView):
    model = Parts
    context_object_name = 'parts_list'

    def get_context_data(self, **kwargs):
        context = super(CatalogPartsView, self).get_context_data(**kwargs)
        context['parts_list'] = Parts.objects.all()
        return context


class CatalogOilsView(BaseCatalogView):
    model = Oils
    context_object_name = 'oils_list'

    def get_context_data(self, **kwargs):
        context = super(CatalogOilsView, self).get_context_data(**kwargs)
        context['oils_list'] = Oils.objects.all()
        return context


class CatalogFiltersView(BaseCatalogView):
    model = Filters
    context_object_name = 'filters_list'

    def get_context_data(self, **kwargs):
        context = super(CatalogFiltersView, self).get_context_data(**kwargs)
        context['filters_list'] = Filters.objects.all()
        return context


def get_part_info(request):
    if request.is_ajax():
        part_id = int(request.GET.get('id'))
        filtered_part = Parts.objects.get(id=part_id)
        html = render_to_string('modal-part.html', {'part': filtered_part})
        return HttpResponse(html)
    else:
        raise HttpResponseServerError


def get_filter_info(request):
    if request.is_ajax():
        filter_id = int(request.GET.get('id'))
        filtered_filter = Filters.objects.get(id=filter_id)
        html = render_to_string('modal-filter.html', {'filter': filtered_filter})
        return HttpResponse(html)
    else:
        raise HttpResponseServerError


def get_oil_info(request):
    if request.is_ajax():
        oil_id = int(request.GET.get('id'))
        filtered_oil = Oils.objects.get(id=oil_id)
        html = render_to_string('modal-oil.html', {'oil': filtered_oil})
        return HttpResponse(html)
    else:
        raise HttpResponseServerError


def get_search_result(request):
    slider = Slider.objects.all()
    form = ContactForm
    if 'search' in request.GET:
        sr = str(request.GET.get('search'))
        parts_list = Parts.objects.filter(
            Q(name__icontains=sr) | Q(brand__icontains=sr) | Q(cat_num__icontains=sr) | Q(
                original_cat_num__icontains=sr) | Q(applicability__icontains=sr)
        )
        oils_list = Oils.objects.filter(
            Q(name__icontains=sr) | Q(brand__icontains=sr) | Q(cat_num__icontains=sr) | Q(viscosity__icontains=sr) | Q(
                oil_type__icontains=sr)
        )
        filters_list = Filters.objects.filter(
            Q(name__icontains=sr) | Q(brand__icontains=sr) | Q(cat_num__icontains=sr) | Q(applicability__icontains=sr)
        )
        return render(request, 'shop.html', {'sr': sr,
                                             'parts_list': parts_list,
                                             'oils_list': oils_list,
                                             'filters_list': filters_list,
                                             'slider': slider,
                                             'form': form,
                                             })

shop/templates/feedback.html
{% load crispy_forms_tags %}

<div class="global-container-feedback hidden-sm">
    <div class="container-feedback">
        <p class="feedback-text">
            Наш телефон:
        </p>
        <p class="feedback-text">
            {% if contacts %}
                {% for contact in contacts %}
                    <span> {{ contact.person_phone }}</span>
                {% endfor %}
            {% endif %}
        </p>
        <p class="feedback-text">
            Время работы:
        </p>
        <p class="feedback-text">
            Ежедневно 8:00 - 20:00
        </p>
        <div class="feedback-form">
            <form class="sky-form contact-style add-order-form" id="add-order-form" method="post" action="{% url 'send_order' %}">
                <div class="fieldWrapper row sky-space-20">
                    <div class="col-md-11 col-md-offset-0">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-success contact_btn" type="submit">
                            Отправить сообщение
                        </button>
                    </div>
                </div>
            </form>
        </div>
    <p class="feedback-text">
        * - Поля обязательные для заполнения
    </p>
    </div>
    <div class="fb-feedback"><span class="feedback">Отправить заявку</span></div>
</div>

shop/templates/modal-filter.html
<div class="modal-header" xmlns="http://www.w3.org/1999/html">
    <button data-dismiss="modal" type="button" class="close">
        <i class="fa fa-close"></i>
    </button>
    <div class="modal-name"><h2 id="myModalLabel modal-name">{{ filter.name }}</h2></div>
</div>
<div class="modal-body">

    <div class="modal-slider">
        <ul class="slides">
            {% for item in filter.imagesfilters_set.all %}
                <li class="slide"><img src="{{ item.image_url }}"></li>
            {% endfor %}
        </ul>
    </div>


    <script>
        jQuery('.modal-slider').glide({
            autoplay: false,
            arrows: true,
            nav: true,
            arrowRightText: '',
            arrowLeftText: ''
        });
    </script>

    <br>
    <table class="table table-striped table-bordered table-hover table-condensed">
        <tbody class="modal-table">
        <tr>
            <td class="">Бренд:</td>
            <td class="">{{ filter.brand }}</td>
        </tr>
        {% if filter.cat_num %}
            <tr>
                <td class="">Оригинальный номер:</td>
                <td class="">{{ filter.cat_num }}</td>
            </tr>
        {% endif %}
        <tr>
            <td class="">Применяемость:</td>
            <td class="">{{ filter.applicability }} </td>
        </tr>
        <tr>
            <td class="">Размеры:</td>
            <td class="">{{ filter.size }} </td>
        </tr>
        <tr>
            <td class="">В наличии:</td>
            <td class="">{{ filter.amount }} шт.</td>
        </tr>
        <tr>
            <td class="">Цена:</td>
            <td class="">{{ filter.price }} руб.</td>
        </tr>
        </tbody>
    </table>
</div>
<div class="modal-footer">
    <button data-dismiss="modal" type="button" class="btn btn-danger">Закрыть окно</button>
</div>

shop/templates/modal-oil.html
<div class="modal-header" xmlns="http://www.w3.org/1999/html">
    <button data-dismiss="modal" type="button" class="close">
        <i class="fa fa-close"></i>
    </button>
    <div class="modal-name"><h2 id="myModalLabel modal-name">{{ oil.name }}</h2></div>
</div>
<div class="modal-body">

    <div class="modal-slider">
        <ul class="slides">
            {% for item in oil.imagesoils_set.all %}
                <li class="slide"><img src="{{ item.image_url }}"></li>
            {% endfor %}
        </ul>
    </div>


    <script>
        jQuery('.modal-slider').glide({
            autoplay: false,
            arrows: true,
            nav: true,
            arrowRightText: '',
            arrowLeftText: ''
        });
    </script>

    <br>
    <table class="table table-striped table-bordered table-hover table-condensed">
        <tbody class="modal-table">
        <tr>
            <td class="">Бренд:</td>
            <td class="">{{ oil.brand }}</td>
        </tr>
        {% if oil.cat_num %}
            <tr>
                <td class="">Оригинальный номер:</td>
                <td class="">{{ oil.cat_num }}</td>
            </tr>
        {% endif %}
        <tr>
            <td class="">Объем:</td>
            <td class="">{{ oil.size }} л.</td>
        </tr>
        <tr>
            <td class="">Вязкость:</td>
            <td class="">{{ oil.viscosity }}</td>
        </tr>
        <tr>
            <td class="">Тип масла:</td>
            <td class="">{{ oil.oil_type }}</td>
        </tr>
        <tr>
            <td class="">В наличии:</td>
            <td class="">{{ oil.amount }} шт.</td>
        </tr>
        <tr>
            <td class="">Цена:</td>
            <td class="">{{ oil.price }} руб.</td>
        </tr>
        </tbody>
    </table>
</div>
<div class="modal-footer">
    <button data-dismiss="modal" type="button" class="btn btn-danger">Закрыть окно</button>
</div>

shop/templates/modal-part.html
<div class="modal-header" xmlns="http://www.w3.org/1999/html">
    <button data-dismiss="modal" type="button" class="close">
        <i class="fa fa-close"></i>
    </button>
    <div class="modal-name"><h2 id="myModalLabel modal-name">{{ part.name }}</h2></div>
</div>
<div class="modal-body">

    <div class="modal-slider">
        <ul class="slides">
            {% for item in part.imagesparts_set.all %}
                <li class="slide"><img src="{{ item.image_url }}"></li>
            {% endfor %}
        </ul>
    </div>


    <script>
        jQuery('.modal-slider').glide({
            autoplay: false,
            arrows: true,
            nav: true,
            arrowRightText: '',
            arrowLeftText: ''
        });
    </script>

    <br>
    <table class="table table-striped table-bordered table-hover table-condensed">
        <tbody class="modal-table">
        <tr>
            <td class="">Бренд:</td>
            <td class="">{{ part.brand }}</td>
        </tr>
        <tr>
            <td class="">Каталожный номер:</td>
            <td class="">{{ part.cat_num }}</td>
        </tr>
        {% if part.original_cat_num %}
            <tr>
                <td class="">Оригинальный номер:</td>
                <td class="">{{ part.original_cat_num }}</td>
            </tr>
        {% endif %}
        <tr>
            <td class="">Применяемость:</td>
            <td class="">{{ part.applicability }}</td>
        </tr>
        <tr>
            <td class="">В наличии:</td>
            <td class="">{{ part.amount }} шт.</td>
        </tr>
        <tr>
            <td class="">Цена:</td>
            <td class="">{{ part.price }} руб.</td>
        </tr>
        </tbody>
    </table>
</div>
<div class="modal-footer">
    <button data-dismiss="modal" type="button" class="btn btn-danger">Закрыть окно</button>
</div>

shop/templates/shop.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    PartsMallSpb - Товары
{% endblock %}

{% block content %}

    {% include 'slider.html' %}
    <br>

    <div class="container">
    <div class="catalog-buttons">
        <a href="{% url 'catalog' %}" class="btn btn-default btn-cat">Все товары</a>
        <a href="{% url 'catalog_parts' %}" class="btn btn-default btn-cat">Запасные части</a>
        <a href="{% url 'catalog_filters' %}" class="btn btn-default btn-cat">Фильтра</a>
        <a href="{% url 'catalog_oils' %}" class="btn btn-default btn-cat">Масла</a>
    </div>
    <br>
    {% if sr %}
        <h3 class="search-res-title">Результаты поиска по запросу <span class="search-res">{{ sr }}</span></h3>
    {% endif %}
    {% if parts_list %}
        {% include 'parts/part_catalog_item.html' %}
    {% endif %}

    {% if oils_list %}
        {% include 'parts/oil_catalog_item.html' %}
    {% endif %}

    {% if filters_list %}
        {% include 'parts/filter_catalog_item.html' %}
    {% endif %}
    </div>
{% endblock %}